### ISSUE TITLE
Flickering screen in mame using Catalina

### ISSUE THREAD

**Issue by schizophobe** [OpenEmu/UME-Core#10]
When using the Mame section under Catalina, the screen flickers a lot on most games.  Regardless of changing filters.  All the other emulators seem fine.  And Mame worked perfect under previous MacOS.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

When using the Mame section under Catalina, the screen flickers a lot on most games.  Regardless of changing filters.  All the other emulators seem fine.  And Mame worked perfect under previous MacOS.

# Expected Behavior

Used to work fine with no flickers in previous Mac OS versions

# Debugging Information

- OpenEmu Version: 2.09.1 Experimental 
- macOS Version: Catalina 10.15

**Comment by clobber** [comment]
https://github.com/OpenEmu/UME-Core/issues/2

This is a result of OpenGL bugs on some hardware with our old MAME core plugin. A future MAME core plugin update will no longer use OpenGL so this will not be a problem, but Arcade/MAME is still generally unsupported and we recommend to use MAME standalone.
