### ISSUE TITLE
Update to MAME 0.218

### ISSUE THREAD

**Issue by benjamin-lewandowski** [OpenEmu/UME-Core#11]
MAME was Updated to 0.218 on 02 Feb 2020 https://www.mamedev.org/?p=479

**Comment by clobber** [comment]
Yes... we are aware. We’re not always going to be keeping up with MAME’s monthly releases. Maintaining this core plugin is more work than you can imagine.

**Comment by benjaminlewandowski** [comment]
0.219 https://www.mamedev.org/?p=480
0.220 https://www.mamedev.org/?p=481
0.221 https://www.mamedev.org/?p=482
0.222 https://www.mamedev.org/?p=483
0.223 https://www.mamedev.org/?p=484
0.224 https://www.mamedev.org/?p=485

sadly i still have to maintain 2 complete mame sets (retroarch/mame + openemu).

**Comment by stuartcarnie** [comment]
MAME 0.224 as of baec92eba793980f505004cdbc06fc6550670abd
