### ISSUE TITLE
"The MAME core has quit unexpedcatedly" (message recieved today when trying all Arcade roms 

### ISSUE THREAD

**Issue by 1010222** [OpenEmu/UME-Core#13]
Greetings and happy new year,

As of this evening, I am suddenly recieving this message when trying to play any arcade rom running openemu (the experimental version) on an iMac (macOS mojave - version 10.14.6), and even after restarting the machine:

"The MAME core has quit unexpedcetedly" - followed by instructions on sending feedback.
 Up until now the program has been running just fine

Is anyone else experiencing this, or knows what I should do? Other concoles (and there cores) are running fine. Thanks in advance,
Adam

**Comment by clobber** [comment]
You can try deleting the MAME core plugin and redownloading it in case your MAME 0.277 core update was corrupted. Without actual details and a crash log, we cannot help you beyond that.

**Comment by 1010222** [comment]
@clobber ok thank you very much for the quick feedback. Will give it a go. My machine has just promptly asked for an OS-update to Catalina all of a sudden too, so maybe that affected it somehow. Will in any case try what you said. Cheers.

**Comment by 1010222** [comment]
All ok and back to norm with the OS-upgrade. Best wishes.

**Comment by clobber** [comment]
Turns out the problem is the core plugin was built targeting 10.15, so it will not run on 10.14. I am rebuilding so it targets 10.14 as a minimum and will reissue a MAME plugin update.

**Comment by chilledbreeze7** [comment]
@clobber thanks for looking into this and look forward to getting the Mame update. Awesome work man and much appreciated!!

**Comment by clobber** [comment]
This is fixed now.

Restart the app and an updated MAME core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for MAME 0.227.0.1

**Comment by Nappa5150** [comment]
NICE!... confirm, it works again... except for saved states, but no problem 😉.
THANKYOU again @clobber

**Comment by stuartcarnie** [comment]
@Nappa5150 unfortunately, MAME changes the save state format from time to time. Unfortunately, this was one of those times, so previous ones do not work. I have confirmed that 0.227 can save and restore correctly, just not compatible with 0.225 or earlier versions.

**Comment by Nappa5150** [comment]
I see, thank you @stuartcarnie, but no matter for the old saved states.
But the only thing I have done is to delete them otherwise OpenEmu continue to alert me with an error of incompatibility.
👍
