### ISSUE TITLE
Mame core image flickering problems

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/UME-Core#2]
https://github.com/OpenEmu/OpenEmu/issues/1089

Hi there:

I'm trying the mame core but there are some video flickering as you can see on this video:

https://www.youtube.com/watch?v=bJC0rpvOsM8

If you need more info, just ask.

xabi

**Comment by thomas-corte** [comment]
I'm seeing similar flickering issues with the latest OpenEmu version (2.0.9.1) on a non-retina iMac (iMac (27-inch, Late 2013)) with an NVIDIA GeForce GTX 775M 2 GB graphics card. On a retina MacBook Pro the issue doesn't show with the same OpenEmu version.

**Comment by stuartcarnie** [comment]
@mrvacbob presumably this is no longer an issue with the new MAME core and OE render pipeline?

**Comment by mrvacbob** [comment]
Probably not.
