### ISSUE TITLE
Application will freeze if files/romset is not found 

### ISSUE THREAD

**Issue by mbroncano** [OpenEmu/UME-Core#6]
It seems that some logic change was introduced when updating the Core API. The best way to handle this that I found out is to return an error when loadFileAtPath:error in MAMEGameCore fails, similar to what HiganGameCore does.

**Comment by clobber** [comment]
This does not appear to be a problem as of OpenEmu 2.0.6.1 and our MAME core plugin 0.149.3. If a required dump is missing (e.g. mslug.zip missing neogeo.zip) loading fails with an alert "The emulator could not load ROM" and logs audit fail output in Console.
