### ISSUE TITLE
Autosave states possibly not restoring on load; freezes requiring force quit.

### ISSUE THREAD

**Issue by clobber** [OpenEmu/UME-Core#7]
Haven't yet checked with 0.169, but broken in 0.149 since OE 2.0.2.

**Comment by BenitolSantos** [comment]
Possible workaround https://github.com/OpenEmu/OpenEmu/issues/2589

**Comment by clobber** [comment]
https://github.com/OpenEmu/UME-Core/commit/999565397d3fb867e68a958a7e468aa59059d168
