### ISSUE TITLE
Error log?

### ISSUE THREAD

**Issue by gerardvanschip** [OpenEmu/UME-Core#8]
With regular mame you get some output when its loading roms but within openemu there is no feedback. Is there a way to see what it does behind the scenes so I can troubleshoot why it wont load certain roms?

**Comment by copenhas** [comment]
I was running into some problems as well, but following one of the troubleshooting pages helps.
https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Console-and-crash-reports

OpenEmu seems to log out using the syslog and you can use Console.app to view and filter the logs as they come in.

**Comment by clobber** [comment]
https://github.com/OpenEmu/UME-Core/commit/d548c87d85dbbce9351cd6fdd7ef06c7f0e0d264
